version: "3.9"

services:
  app:
    container_name: book_api
    build:
      context: ./..
      dockerfile: deployments/Dockerfile
    ports:
      - "12342:12342"
    env_file:
      - ../configs/config.env
    networks:
      - network
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    container_name: api
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: book
    volumes:
      - ../assets/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
    restart: always

  adminer:
    image: adminer
    container_name: api-adminer
    restart: always
    ports:
      - "17860:8080"
    networks:
      - network
    depends_on:
      - postgres

networks:
  network:
    driver: bridge